### ISSUE TITLE
CSS homework1

### ISSUE THREAD

**Issue by chnbohwr** [lucianlee1311/training#1]
建議拿掉 bootstrap
建議符合圖片比例

**Comment by chnbohwr** [comment]
![image](https://user-images.githubusercontent.com/6761222/36848558-8c5dcfac-1d9c-11e8-9452-090e0935d488.png)
header 裡面的內容沒有垂直對齊
header 可以再減少層次，例如拿掉 global-nav

---

![image](https://user-images.githubusercontent.com/6761222/36849196-53b15780-1d9e-11e8-84e6-bf58ee7c5780.png)
這邊請再把 padding 調整好，字斷成兩行了

---

![image](https://user-images.githubusercontent.com/6761222/36849359-d31f48ce-1d9e-11e8-99a0-98fcb31b5e99.png)
 與其他與其他元素之間的距離，建議用 margin 來區隔

---

![image](https://user-images.githubusercontent.com/6761222/36849584-61fef72e-1d9f-11e8-8365-ff8150bee173.png)
不要用 padding 去置中還有分散，請用 flexbox 來置中

---
![image](https://user-images.githubusercontent.com/6761222/36849422-00e2d262-1d9f-11e8-8552-381665f1c95c.png)
不要用 padding 來置中，因為這樣會算不準，請用 flexbox 來置中

---

![image](https://user-images.githubusercontent.com/6761222/36850105-cd996e5a-1da0-11e8-9081-6f7ac2904d53.png)
這邊不要用左中右佈局 應該用 flex 的 justify-content 來做置中

---

![image](https://user-images.githubusercontent.com/6761222/36850616-3fa05094-1da2-11e8-830e-af74c0701808.png)
tip-item-half, tip-item-full不理想，請思考更好的做法 

---

最後就是思考一下 classname 怎樣取名有意義，假設有一個新人要接手你的這個網站，看到很多 main-row main-top main-area ，他會不知所措，所以盡量把你的 classname 取的有意義一點

**Comment by lucianlee1311** [comment]
1. 修正 header 裡面的內容垂直對齊
2. 修正 改用text-decoration: underline;
3. 修正 改用margin來區隔
4. 修正 改用flexbox置中
5. 修正 改用flexbox置中
6. 修正 改用flexbox置中
7. 修正 改用position: absolute;
