### ISSUE TITLE
CSS homework2

### ISSUE THREAD

**Issue by chnbohwr** [lucianlee1311/training#2]
![image](https://user-images.githubusercontent.com/6761222/36882410-a9c437b2-1e0e-11e8-931c-34717733ed06.png)
這邊沒有跟原圖一致，請修改

---

![image](https://user-images.githubusercontent.com/6761222/36882478-1dff0f44-1e0f-11e8-8683-7a04c527cb37.png)
這邊要再仔細跟原圖比對一下細節部分字型不要求，但是顏色跟大小還有間距要正確

---

![image](https://user-images.githubusercontent.com/6761222/36882518-56403b30-1e0f-11e8-9c18-ef3722d69b0a.png)

不應該是 child 裡面放 reverse ， 應該要 parent element 用 reverse 來控制

---

![image](https://user-images.githubusercontent.com/6761222/36882564-92db62d6-1e0f-11e8-8fb9-e100de3530e1.png)

應該要由外層的 footer 做 padding

---

![image](https://user-images.githubusercontent.com/6761222/36882599-cd930226-1e0f-11e8-893f-d439c7d31e11.png)

過度包裝

---

![image](https://user-images.githubusercontent.com/6761222/36882616-e7cfe208-1e0f-11e8-8438-a01a8ca247b5.png)

思考 classname 命名

**Comment by lucianlee1311** [comment]
1. 修正 寬度,陰影
2. 修正 顏色,大小,間距
3. 修正 reverse改放到parent element
4. 修正 改用外層的footer做padding
5. 修正 刪除container
6. 修正 classname

**Comment by chnbohwr** [comment]
ok
