### ISSUE TITLE
week2_javascript homework3

### ISSUE THREAD

**Issue by lucianlee1311** [lucianlee1311/training#6]
1. 修正2~7 共用變數放到最上方
2. 修正2~7 使用Promise搭配fetch使用
3. 修正2~7 fetch取到的陣列，再另外新增一份使用
4. 修正2 使用find
5. 修正5 使用Object.assign()去更新{}內容

**Comment by chnbohwr** [comment]
```
const app = () => new Promise((resolve, reject) => {
```
再取一個好一點的名字

---

**Comment by lucianlee1311** [comment]
修正 名稱getAlbumData

**Comment by chnbohwr** [comment]
用 async await 傳出錯誤的方式錯了

https://stackoverflow.com/questions/42453683/how-to-reject-in-async-await-syntax

**Comment by lucianlee1311** [comment]
修正 catch傳出錯誤方式

**Comment by lucianlee1311** [comment]
修正 因fetch catch的error已經是Error, 所以直接throw, 不必再new Error()

**Comment by chnbohwr** [comment]
ok 自己 colse issue
