### ISSUE TITLE
javascript homework4

### ISSUE THREAD

**Issue by chnbohwr** [lucianlee1311/training#8]
```
const cloneArray = (a) => {
```

重新命名一下，名字不好

**Comment by chnbohwr** [comment]
```
Date.prototype.format = function () {
```

為什麼這邊不能用 ()=>{}   請補上回答

**Comment by chnbohwr** [comment]
```
sayhi() {
```
這邊可不可以用箭頭函式？ 為什麼？  請補上回答

**Comment by lucianlee1311** [comment]
1. 修正 名稱getCloneObjectText
2. 箭頭函式中的this會指向window下, 所以若window下沒宣告，箭頭函式中使用this變數或方法時會取得undefined
3. 類別中的方法sayhi()效果等同於prototype.sayhi = function(){}, 所以跟2會有相同情形

**Comment by chnbohwr** [comment]
ok good
